import { Option } from "@/types";

export const sideBarOptions: Option[] = [
  {
    title: "Reset All and Randomize Buttons",
    subTitle: "Won't be display don't worry about it",
    localStorageId: "null",
    optionType: "ResetColorsAndRandomize",
    tileId: "globalSettings",
  },
  {
    title: "Background color",
    subTitle: "Controls the theme background color of the main page",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "globalSettings",
  },
  {
    title: "Drop shadow",
    subTitle: "Controls the drop shadow of all the tiles.",
    localStorageId: "dropShadow",
    optionType: "DropShadowInput",
    tileId: "globalSettings",
  },
  {
    title: "Border",
    subTitle: "Controls the border of all the tiles.",
    localStorageId: "tileBorder",
    optionType: "BorderSelect",
    tileId: "globalSettings",
  },
  {
    title: "Border Radius",
    subTitle: "Controls the border radius of all the tiles",
    localStorageId: "borderRadius",
    optionType: "BorderRadiusInput",
    tileId: "globalSettings",
  },
  {
    title: "Border Color",
    subTitle: "Controls the color of the border for all of the tiles",
    localStorageId: "borderColor",
    optionType: "ColorPicker",
    tileId: "globalSettings",
  },
  {
    title: "Grid Gap",
    subTitle: "Controls the grip gap of all the tiles",
    localStorageId: "gridGap",
    optionType: "GridGapInput",
    tileId: "globalSettings",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile1",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile1",
  },
  {
    title: "Bonsai base color",
    subTitle: "Color of the bonsai base",
    localStorageId: "bonsaiBaseColor",
    optionType: "ColorPicker",
    tileId: "tile1",
  },
  {
    title: "Bonsai trunk color",
    subTitle: "Color of the bonsai trunk",
    localStorageId: "bonsaiTrunkColor",
    optionType: "ColorPicker",
    tileId: "tile1",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile1",
  },
  {
    title: "Hacker News Feed Type",
    subTitle: "What type of feed do you want to see from Hacker News?",
    localStorageId: "hackerNewsFeedType",
    optionType: "HackerNewsFeedType",
    tileId: "tile1",
  },
  {
    title: "Spotify Top Artists Time Length",
    subTitle: "How long back do you want to search over?",
    localStorageId: "spotifyArtistSearchTimeLength",
    optionType: "SpotifyTopArtistsTimeLength",
    tileId: "tile1",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "MediumTileTypePicker",
    tileId: "tile1",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile2",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile2",
  },
  {
    title: "City for UV data",
    subTitle: "Name of the city you want the UV data for",
    localStorageId: "cityForUv",
    optionType: "CityInputForUV",
    tileId: "tile2",
  },
  {
    title: "City for weather forecast",
    subTitle: "Name of the city you want the weather forecast for",
    localStorageId: "cityForWeather",
    optionType: "CityInputForWeather",
    tileId: "tile2",
  },
  {
    title: "Type of tile",
    subTitle: "Type of tile you want to display",
    localStorageId: "tileType",
    optionType: "LargeTileTypePicker",
    tileId: "tile2",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile3",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile3",
  },
  {
    title: "Bonsai base color",
    subTitle: "Color of the bonsai base",
    localStorageId: "bonsaiBaseColor",
    optionType: "ColorPicker",
    tileId: "tile3",
  },
  {
    title: "Bonsai trunk color",
    subTitle: "Color of the bonsai trunk",
    localStorageId: "bonsaiTrunkColor",
    optionType: "ColorPicker",
    tileId: "tile3",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile3",
  },
  {
    title: "Hacker News Feed Type",
    subTitle: "What type of feed do you want to see from Hacker News?",
    localStorageId: "hackerNewsFeedType",
    optionType: "HackerNewsFeedType",
    tileId: "tile3",
  },
  {
    title: "Spotify Top Artists Time Length",
    subTitle: "How long back do you want to search over?",
    localStorageId: "spotifyArtistSearchTimeLength",
    optionType: "SpotifyTopArtistsTimeLength",
    tileId: "tile3",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "MediumTileTypePicker",
    tileId: "tile3",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile4",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile4",
  },
  {
    title: "Bonsai base color",
    subTitle: "Color of the bonsai base",
    localStorageId: "bonsaiBaseColor",
    optionType: "ColorPicker",
    tileId: "tile4",
  },
  {
    title: "Bonsai trunk color",
    subTitle: "Color of the bonsai trunk",
    localStorageId: "bonsaiTrunkColor",
    optionType: "ColorPicker",
    tileId: "tile4",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile4",
  },
  {
    title: "Hacker News Feed Type",
    subTitle: "What type of feed do you want to see from Hacker News?",
    localStorageId: "hackerNewsFeedType",
    optionType: "HackerNewsFeedType",
    tileId: "tile4",
  },
  {
    title: "Spotify Top Artists Time Length",
    subTitle: "How long back do you want to search over?",
    localStorageId: "spotifyArtistSearchTimeLength",
    optionType: "SpotifyTopArtistsTimeLength",
    tileId: "tile4",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "MediumTileTypePicker",
    tileId: "tile4",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile5",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile5",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "LongTileTypePicker",
    tileId: "tile5",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile6",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile6",
  },
  {
    title: "Bonsai base color",
    subTitle: "Color of the bonsai base",
    localStorageId: "bonsaiBaseColor",
    optionType: "ColorPicker",
    tileId: "tile6",
  },
  {
    title: "Bonsai trunk color",
    subTitle: "Color of the bonsai trunk",
    localStorageId: "bonsaiTrunkColor",
    optionType: "ColorPicker",
    tileId: "tile6",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile6",
  },
  {
    title: "Hacker News Feed Type",
    subTitle: "What type of feed do you want to see from Hacker News?",
    localStorageId: "hackerNewsFeedType",
    optionType: "HackerNewsFeedType",
    tileId: "tile6",
  },
  {
    title: "Spotify Top Artists Time Length",
    subTitle: "How long back do you want to search over?",
    localStorageId: "spotifyArtistSearchTimeLength",
    optionType: "SpotifyTopArtistsTimeLength",
    tileId: "tile6",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "MediumTileTypePicker",
    tileId: "tile6",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile7",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile7",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    optionType: "CityInputForWeather",
    tileId: "tile7",
  },
  {
    title: "Stock ticker",
    subTitle: "Ticker that you want to see the stock info for, in capitals",
    localStorageId: "stockName",
    optionType: "SmallStockInput",
    tileId: "tile7",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "SmallTileTypePicker",
    tileId: "tile7",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile8",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile8",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    optionType: "CityInputForWeather",
    tileId: "tile8",
  },
  {
    title: "Stock ticker",
    subTitle: "Ticker that you want to see the stock info for, in capitals",
    localStorageId: "stockName",
    optionType: "SmallStockInput",
    tileId: "tile8",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "SmallTileTypePicker",
    tileId: "tile8",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile9",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile9",
  },
  {
    title: "City for weather forecast",
    subTitle: "Name of the city you want the weather forecast for",
    localStorageId: "cityForWeather",
    optionType: "CityInputForWeather",
    tileId: "tile9",
  },
  {
    title: "City for UV data",
    subTitle: "Name of the city you want the UV data for",
    localStorageId: "cityForUv",
    optionType: "CityInputForUV",
    tileId: "tile9",
  },
  {
    title: "Type of tile",
    subTitle: "Type of tile you want to display",
    localStorageId: "tileType",
    optionType: "LargeTileTypePicker",
    tileId: "tile9",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile10",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile10",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    optionType: "CityInputForWeather",
    tileId: "tile10",
  },
  {
    title: "Stock ticker",
    subTitle: "Ticker that you want to see the stock info for, in capitals",
    localStorageId: "stockName",
    optionType: "SmallStockInput",
    tileId: "tile10",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "SmallTileTypePicker",
    tileId: "tile10",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    optionType: "ColorPicker",
    tileId: "tile11",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    optionType: "ColorPicker",
    tileId: "tile11",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    optionType: "CityInputForWeather",
    tileId: "tile11",
  },
  {
    title: "Stock ticker",
    subTitle: "Ticker that you want to see the stock info for, in capitals",
    localStorageId: "stockName",
    optionType: "SmallStockInput",
    tileId: "tile11",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    optionType: "SmallTileTypePicker",
    tileId: "tile11",
  },
];
