import {Option} from "@/types";

export const sideBarOptions: Option[] = [
  {
    title: "Background color",
    subTitle: "Controls the theme background color of the main page",
    localStorageId: "backgroundColor",
    lightDefault: "#ffffff",
    darkDefault: "#1B202B",
    optionType: "ColorPicker",
    tileId: "globalSettings",
  },
  {
    title: "Drop shadow",
    subTitle: "Controls the drop shadow of all the tiles",
    localStorageId: "dropShadow",
    lightDefault: "",
    darkDefault: "",
    optionType: "DropShadowInput",
    tileId: "globalSettings",
  },
  {
    title: "Border",
    subTitle: "Controls the border of all the tiles",
    localStorageId: "tileBorder",
    lightDefault: "",
    darkDefault: "",
    optionType: "BorderSelect",
    tileId: "globalSettings",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#65abc1",
    darkDefault: "#65abc1",
    optionType: "ColorPicker",
    tileId: "tile1",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile1",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile1",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "Hacker News Feed",
    optionType: "MediumTileTypePicker",
    tileId: "tile1",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#E89C4B",
    darkDefault: "#E89C4B",
    optionType: "ColorPicker",
    tileId: "tile2",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile2",
  },
  {
    title: "Tile Type",
    subTitle: "Type of tile you want to display",
    localStorageId: "tileType",
    defaultSetting: "Strava Graph",
    optionType: "LargeTileTypePicker",
    tileId: "tile2",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#9AB899",
    darkDefault: "#9AB899",
    optionType: "ColorPicker",
    tileId: "tile3",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile3",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile3",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "None",
    optionType: "MediumTileTypePicker",
    tileId: "tile3",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#E89C4B",
    darkDefault: "#E89C4B",
    optionType: "ColorPicker",
    tileId: "tile4",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile4",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile4",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "Reddit Feed",
    optionType: "MediumTileTypePicker",
    tileId: "tile4",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#F06808",
    darkDefault: "#F06808",
    optionType: "ColorPicker",
    tileId: "tile5",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile5",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#E89C4B",
    darkDefault: "#E89C4B",
    optionType: "ColorPicker",
    tileId: "tile6",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile6",
  },
  {
    title: "Reddit feed subreddit",
    subTitle: "Subreddit you want to see the posts from",
    localStorageId: "subReddit",
    optionType: "SubRedditPicker",
    tileId: "tile6",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "Reddit Feed",
    optionType: "MediumTileTypePicker",
    tileId: "tile6",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#65abc1",
    darkDefault: "#65abc1",
    optionType: "ColorPicker",
    tileId: "tile7",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile7",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    defaultSetting: "Wellington",
    optionType: "CityInput",
    tileId: "tile7",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "Weather",
    optionType: "SmallTileTypePicker",
    tileId: "tile7",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#9AB899",
    darkDefault: "#9AB899",
    optionType: "ColorPicker",
    tileId: "tile8",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile8",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    defaultSetting: "Wellington",
    optionType: "CityInput",
    tileId: "tile8",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "None",
    optionType: "SmallTileTypePicker",
    tileId: "tile8",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#E89C4B",
    darkDefault: "#E89C4B",
    optionType: "ColorPicker",
    tileId: "tile9",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile9",
  },
  {
    title: "Tile Type",
    subTitle: "Type of tile you want to display",
    localStorageId: "tileType",
    defaultSetting: "Large Spotify Tile",
    optionType: "LargeTileTypePicker",
    tileId: "tile9",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#9AB899",
    darkDefault: "#9AB899",
    optionType: "ColorPicker",
    tileId: "tile10",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile10",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    defaultSetting: "Wellington",
    optionType: "CityInput",
    tileId: "tile10",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "Time",
    optionType: "SmallTileTypePicker",
    tileId: "tile10",
  },
  {
    title: "Background color",
    subTitle: "Background color of the tile",
    localStorageId: "backgroundColor",
    lightDefault: "#65abc1",
    darkDefault: "#65abc1",
    optionType: "ColorPicker",
    tileId: "tile11",
  },
  {
    title: "Text color",
    subTitle: "Text color of the tile",
    localStorageId: "textColor",
    lightDefault: "#ffffff",
    darkDefault: "#222222",
    optionType: "ColorPicker",
    tileId: "tile11",
  },
  {
    title: "City for weather",
    subTitle: "Name of the city you want the weather for",
    localStorageId: "cityForWeather",
    defaultSetting: "Wellington",
    optionType: "CityInput",
    tileId: "tile11",
  },
  {
    title: "Type of tile",
    subTitle: "Choose what you want this tile to display",
    localStorageId: "tileType",
    defaultSetting: "Theme Picker",
    optionType: "SmallTileTypePicker",
    tileId: "tile11",
  },
];
