import { UserSettings } from "@/types";
import { defaultGridLayout } from "./gridLayout";

export const defaultSettings: UserSettings = {
  themes: [
    {
      themeName: "colored light",
      downloadedFromMarketplace: false,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor: "#ffffff",
        textColor: "#222222",
        tileType: "None",
        dropShadow: "",
        tileBorder: "",
        sidebarBackgroundColor: "#eeeeee",
        themePickerBubbleColor:
          "linear-gradient(90deg, white 50%, #E89B4B 50%);",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tileLayout: defaultGridLayout,
      tiles: [
        {
          tileId: 0,
          backgroundColor: "#65abc1",
          textColor: "#ffffff",
          tileType: "Hacker News Feed",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "#E89C4B",
          textColor: "#ffffff",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "#9AB899",
          textColor: "#ffffff",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "#65abc1",
          textColor: "#ffffff",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "#F06808",
          textColor: "#ffffff",
          tileType: "Search Bar",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "#E89C4B",
          textColor: "#ffffff",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#fff",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "#E89C4B",
          textColor: "#ffffff",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "#65abc1",
          textColor: "#ffffff",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "#9AB899",
          textColor: "#ffffff",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "#E89C4B",
          textColor: "#ffffff",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "#65abc1",
          textColor: "#ffffff",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "colored dark",
      downloadedFromMarketplace: false,
      tileLayout: defaultGridLayout,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor: "#1B202B",
        textColor: "#fff",
        subTextColor: "#ddd",
        tileType: "None",
        dropShadow: "",
        tileBorder: "",
        sidebarBackgroundColor: "#33393D",
        themePickerBubbleColor:
          "linear-gradient(90deg, black 50%, #E89B4B 50%);",
        sidebarBorderColor: "#666",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tiles: [
        {
          tileId: 0,
          backgroundColor: "#65abc1",
          textColor: "#222222",
          tileType: "Twitter Feed Tile",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "#E89C4B",
          textColor: "#222222",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "#9AB899",
          textColor: "#222222",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "#E89C4B",
          textColor: "#222222",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "#F06808",
          textColor: "#222222",
          tileType: "Day Planner",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "#E89C4B",
          textColor: "#222222",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#fff",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "#65abc1",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "#9AB899",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "#E89C4B",
          textColor: "#222222",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "#9AB899",
          textColor: "#222222",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "#65abc1",
          textColor: "#222222",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "Wavy",
      downloadedFromMarketplace: false,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor: "url(/wavy.jpeg)",
        textColor: "#222222",
        tileType: "None",
        dropShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
        tileBorder: "1px solid rgba(255, 255, 255, 0.3)",
        sidebarBackgroundColor: "#eeeeee",
        themePickerBubbleColor: "linear-gradient(360deg, blue 50%, white 50%);",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tileLayout: defaultGridLayout,
      tiles: [
        {
          tileId: 0,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Twitter Feed Tile",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Day Planner",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#202020",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "Pink",
      downloadedFromMarketplace: false,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor:
          "linear-gradient(to bottom right, #ABA1EE , #F29AD8) fixed",
        textColor: "#222222",
        tileType: "None",
        dropShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
        tileBorder: "1px solid rgba(255, 255, 255, 0.3)",
        sidebarBackgroundColor: "#eeeeee",
        themePickerBubbleColor:
          "linear-gradient(90deg, #ABA1EE 50%, #f882ff 50%);",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tileLayout: defaultGridLayout,
      tiles: [
        {
          tileId: 0,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Hacker News Feed",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Day Planner",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#202020",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "basic light",
      downloadedFromMarketplace: false,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor: "white",
        textColor: "#222222",
        tileType: "None",
        dropShadow: "",
        tileBorder: "1px solid black",
        sidebarBackgroundColor: "#eeeeee",
        themePickerBubbleColor: "white",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tileLayout: defaultGridLayout,
      tiles: [
        {
          tileId: 0,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Hacker News Feed",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Search Bar",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#202020",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "#ffffff",
          textColor: "#222222",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "basic dark",
      downloadedFromMarketplace: false,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor: "#000",
        textColor: "#fff",
        subTextColor: "#ddd",
        tileType: "None",
        sidebarBackgroundColor: "#33393D",
        themePickerBubbleColor: "black",
        sidebarBorderColor: "#666",
        dropShadow: "2px 2px 6px rgba(0,0,0,.3)",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tileLayout: defaultGridLayout,
      tiles: [
        {
          tileId: 0,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Hacker News Feed",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Search Bar",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#fff",
          bonsaiBaseColor: "#fff",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "#1A1C1D",
          textColor: "#E0E0E0",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "glassmorphism light",
      downloadedFromMarketplace: false,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor:
          "linear-gradient(160deg, #0093E9 0%, #80D0C7 100%) fixed",
        textColor: "#222222",
        tileType: "None",
        dropShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
        tileBorder: "1px solid rgba(255, 255, 255, 0.3)",
        sidebarBackgroundColor: "#eeeeee",
        themePickerBubbleColor:
          "linear-gradient(90deg, white 50%, #77C9CA 50%);",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tileLayout: defaultGridLayout,
      tiles: [
        {
          tileId: 0,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Twitter Feed Tile",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Day Planner",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#202020",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
    {
      themeName: "glassmorphism dark",
      downloadedFromMarketplace: false,
      tileLayout: defaultGridLayout,
      globalSettings: {
        tileId: -1,
        tileSize: "medium",
        backgroundColor:
          "linear-gradient(160deg, black 0%, #80D0C7 100%) fixed",
        textColor: "#fff",
        tileType: "None",
        dropShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
        tileBorder: "1px solid rgba(255, 255, 255, 0.3)",
        sidebarBackgroundColor: "#33393D",
        themePickerBubbleColor:
          "linear-gradient(90deg, black 50%, #2E4C49 50%);",
        subTextColor: "#ddd",
        sidebarBorderColor: "#666",
        borderRadius: "15px",
        gridGap: "16px",
      },
      tiles: [
        {
          tileId: 0,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Twitter Feed Tile",
          hackerNewsFeedType: "Top",
          tileSize: "medium",
        },
        {
          tileId: 1,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Weather Tile",
          tileSize: "large",
        },
        {
          tileId: 2,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Todo List",
          tileSize: "medium",
        },
        {
          tileId: 3,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Reddit Feed",
          tileSize: "medium",
        },
        {
          tileId: 4,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Day Planner",
          tileSize: "long",
        },
        {
          tileId: 5,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Bonsai",
          bonsaiTrunkColor: "#202020",
          bonsaiBaseColor: "#000",
          tileSize: "medium",
        },
        {
          tileId: 6,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 7,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Small Stock Tile",
          tileSize: "small",
        },
        {
          tileId: 8,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Large Spotify Tile",
          tileSize: "large",
        },
        {
          tileId: 9,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Time",
          tileSize: "small",
        },
        {
          tileId: 10,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          textColor: "#222222",
          tileType: "Theme Picker",
          tileSize: "small",
        },
      ],
    },
  ],
};
